logging:
  config: classpath:log-config/log4j2-dev.xml
server:
  port: 8181
spring:
  datasource:
    username: root
    password: P@sswrd$1
    url: jdbc:mysql://hongyitest.kisara.top/test
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5